services:
  weatherapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Consul__Address=http://consul:8500
    ports:
      - "5032:5032"
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GlobalConfiguration__ServiceDiscoveryProvider__Host=consul
    ports:
      - "2999:2999"
  consul:
    ports:
      - "8500:8500"
      - "8502:8502"
      - "8600:8600"
      - "8301:8301"
      - "8302:8302"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    restart: always  